In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

In [13]:
array1 = np.array([1, 2, 3, 4, 5])
array1

array([1, 2, 3, 4, 5])

In [14]:
print(type(array1))

<class 'numpy.ndarray'>


# Execution time differences

## Lists 

In [7]:
import time

In [9]:
revenues  = [5000, 10000, 15000, 20000, 25000]

In [23]:
initial_time1 = time.time()
sum = 0

for i in revenues:
  sum += i

print(sum)
termination_time1 = time.time()

execution_time1 = termination_time1 - initial_time1
print("Execution time: ", execution_time1)

75000
Execution time:  0.006559610366821289


## NumPy

In [24]:
array2 = np.array(revenues)
array2

initial_time2 = time.time()
sum = array2.sum()

print(sum)
termination_time2 = time.time()

execution_time2 = termination_time2 - initial_time2

print("Execution time: ", execution_time2)

75000
Execution time:  0.0026328563690185547


In [25]:
difference = execution_time1 / execution_time2
difference

2.491442542787286

# Memory usage differences

## Lists

In [26]:
x = ["Ben", 500, "Jake", "Liz", 6000]

In [32]:
for element1 in x:
  print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [33]:
arrayx = np.array(x)
arrayx

array(['Ben', '500', 'Jake', 'Liz', '6000'], dtype='<U21')

In [34]:
for element2 in arrayx:
  print(type(element2))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## 2D Arrays

In [35]:
array3 = np.array([[1, 2, 3], [4, 5, 6]])
array3

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
print(array3)

[[1 2 3]
 [4 5 6]]


In [38]:
# Check dimensions
 
array3.ndim

2

In [39]:
# Check shape
array3.shape

(2, 3)

In [40]:
# Check number of elements
array3.size

6